// The Oracle driver lives behind the `oracle` cargo feature; this test
// file is empty when the feature is off so `cargo test --workspace` (no
// features) still discovers and skips it cleanly.

#![cfg(feature = "oracle")]

use std::sync::atomic::{AtomicU64, Ordering};

use tsqlx_core::DriverKind;
use tsqlx_db::{
    execute_script, fetch_overview, fetch_records, fetch_relationships, fetch_table_info,
};
use tsqlx_sql::SqlDocument;

static SCHEMA_SEQ: AtomicU64 = AtomicU64::new(0);

fn ora_url() -> String {
    std::env::var("TSQLX_TEST_ORACLE_URL").expect("TSQLX_TEST_ORACLE_URL is set")
}

/// Oracle "schemas" are users; we can't create+drop arbitrary users
/// per test without sysdba privileges. Instead, all tests run inside
/// the connecting user's schema and namespace their objects with a
/// unique prefix so parallel runs don't collide.
fn unique_prefix(tag: &str) -> String {
    let id = SCHEMA_SEQ.fetch_add(1, Ordering::SeqCst);
    let pid = std::process::id();
    format!("TSQLX_T_{tag}_{pid}_{id}").to_uppercase()
}

async fn drop_table(url: &str, name: &str) {
    let drop = SqlDocument::new(format!(
        "BEGIN \
           EXECUTE IMMEDIATE 'DROP TABLE \"{name}\" CASCADE CONSTRAINTS'; \
         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; \
         END;\n/"
    ));
    let _ = execute_script(DriverKind::Oracle, url, &drop).await;
}

async fn current_schema(url: &str) -> String {
    let doc = SqlDocument::new("SELECT USER FROM dual".to_owned());
    let out = execute_script(DriverKind::Oracle, url, &doc)
        .await
        .expect("USER query");
    out.statements[0].rows[0][0].clone()
}

#[tokio::test]
#[ignore = "requires TSQLX_TEST_ORACLE_URL"]
async fn executes_oracle_script() {
    let url = ora_url();
    let prefix = unique_prefix("EXEC");
    let table = format!("{prefix}_USERS");
    drop_table(&url, &table).await;

    let document = SqlDocument::new(format!(
        "CREATE TABLE \"{table}\" (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(64) NOT NULL);\n\
         /\n\
         INSERT INTO \"{table}\" (name) VALUES ('ada');\n\
         /\n\
         INSERT INTO \"{table}\" (name) VALUES ('grace');\n\
         /\n\
         SELECT id, name FROM \"{table}\" ORDER BY id;\n\
         /"
    ));

    let output = execute_script(DriverKind::Oracle, &url, &document)
        .await
        .expect("oracle script executes");

    let last = output.statements.last().expect("at least one batch");
    assert_eq!(last.rows.len(), 2);
    assert_eq!(last.rows[0][1], "ada");
    assert_eq!(last.rows[1][1], "grace");

    drop_table(&url, &table).await;
}

#[tokio::test]
#[ignore = "requires TSQLX_TEST_ORACLE_URL"]
async fn oracle_overview_lists_tables() {
    let url = ora_url();
    let prefix = unique_prefix("OV");
    let table = format!("{prefix}_T");
    let owner = current_schema(&url).await;
    drop_table(&url, &table).await;

    let setup = SqlDocument::new(format!("CREATE TABLE \"{table}\" (id NUMBER PRIMARY KEY)"));
    execute_script(DriverKind::Oracle, &url, &setup)
        .await
        .expect("setup runs");

    let ov = fetch_overview(DriverKind::Oracle, &url)
        .await
        .expect("overview fetches");
    let our = ov
        .schemas
        .into_iter()
        .find(|s| s.name == owner)
        .expect("owner schema present");
    assert!(our.tables.iter().any(|t| t == &table));

    drop_table(&url, &table).await;
}

#[tokio::test]
#[ignore = "requires TSQLX_TEST_ORACLE_URL"]
async fn oracle_table_info_reports_columns_pk_fk() {
    let url = ora_url();
    let prefix = unique_prefix("TI");
    let users = format!("{prefix}_USERS");
    let orders = format!("{prefix}_ORDERS");
    let owner = current_schema(&url).await;
    drop_table(&url, &orders).await;
    drop_table(&url, &users).await;

    let setup = SqlDocument::new(format!(
        "CREATE TABLE \"{users}\" (id NUMBER PRIMARY KEY, name VARCHAR2(64) NOT NULL);\n\
         /\n\
         CREATE TABLE \"{orders}\" (\n\
            id NUMBER PRIMARY KEY,\n\
            user_id NUMBER NOT NULL,\n\
            CONSTRAINT \"{prefix}_FK\" FOREIGN KEY (user_id) REFERENCES \"{users}\"(id)\n\
         );\n\
         /"
    ));
    execute_script(DriverKind::Oracle, &url, &setup)
        .await
        .expect("setup runs");

    let info = fetch_table_info(DriverKind::Oracle, &url, &owner, &users)
        .await
        .expect("users table info");
    assert!(info
        .columns
        .iter()
        .any(|c| c.name == "NAME" && !c.is_nullable));
    let pk = info.primary_key.expect("pk present");
    assert_eq!(pk.column_names, ["ID"]);

    let oinfo = fetch_table_info(DriverKind::Oracle, &url, &owner, &orders)
        .await
        .expect("orders table info");
    let fk = oinfo
        .foreign_keys
        .iter()
        .find(|fk| fk.name == format!("{prefix}_FK"))
        .expect("fk present");
    assert_eq!(fk.column_names, ["USER_ID"]);
    assert_eq!(fk.referenced_table, users);
    assert_eq!(fk.referenced_columns, ["ID"]);

    drop_table(&url, &orders).await;
    drop_table(&url, &users).await;
}

#[tokio::test]
#[ignore = "requires TSQLX_TEST_ORACLE_URL"]
async fn oracle_relationships_returns_edges() {
    let url = ora_url();
    let prefix = unique_prefix("REL");
    let users = format!("{prefix}_USERS");
    let orders = format!("{prefix}_ORDERS");
    let owner = current_schema(&url).await;
    drop_table(&url, &orders).await;
    drop_table(&url, &users).await;

    let setup = SqlDocument::new(format!(
        "CREATE TABLE \"{users}\" (id NUMBER PRIMARY KEY);\n\
         /\n\
         CREATE TABLE \"{orders}\" (\n\
            id NUMBER PRIMARY KEY,\n\
            user_id NUMBER NOT NULL,\n\
            CONSTRAINT \"{prefix}_FK\" FOREIGN KEY (user_id) REFERENCES \"{users}\"(id)\n\
         );\n\
         /"
    ));
    execute_script(DriverKind::Oracle, &url, &setup)
        .await
        .expect("setup runs");

    let edges = fetch_relationships(DriverKind::Oracle, &url, &owner)
        .await
        .expect("relationships");
    assert!(edges
        .iter()
        .any(|e| e.from_table == orders && e.to_table == users));

    drop_table(&url, &orders).await;
    drop_table(&url, &users).await;
}

#[tokio::test]
#[ignore = "requires TSQLX_TEST_ORACLE_URL"]
async fn oracle_fetch_records_pagination() {
    let url = ora_url();
    let prefix = unique_prefix("REC");
    let table = format!("{prefix}_NUMS");
    let owner = current_schema(&url).await;
    drop_table(&url, &table).await;

    let setup = SqlDocument::new(format!(
        "CREATE TABLE \"{table}\" (n NUMBER PRIMARY KEY);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (1);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (2);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (3);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (4);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (5);\n\
         /\n\
         INSERT INTO \"{table}\" (n) VALUES (6);\n\
         /"
    ));
    execute_script(DriverKind::Oracle, &url, &setup)
        .await
        .expect("setup runs");

    let p0 = fetch_records(DriverKind::Oracle, &url, &owner, &table, 3, 0)
        .await
        .expect("page 0");
    assert_eq!(p0.rows.len(), 3);

    let p1 = fetch_records(DriverKind::Oracle, &url, &owner, &table, 3, 3)
        .await
        .expect("page 1");
    assert_eq!(p1.rows.len(), 3);

    drop_table(&url, &table).await;
}
